### ISSUE TITLE
RangeData objects are deprecated

### ISSUE THREAD

**Issue by SouzaBB** [vplagnol/ExomeDepth#20]
Hello everyone. I'm trying to use ExomeDepth for my CNV analysis but I'm falling on this error:
 ```
"RangedData objects are deprecated. Please migrate your code to use
  GRanges or GRangesList objects instead."
```
I'm using the most recent version of ExomeDepth. The vignette says: "Version 1.1.12: •Updated for GRanges changes." but the error persists.

Does anyone has a fix for this issue?

**Comment by vplagnol** [comment]
Hey @SouzaBB , thanks for this, I think I just fixed it.
Can you run please"
`devtools::install_github("vplagnol/ExomeDepth")`
and tell me whether that fixes your issue? I want to make sure I haven't broken other things before pushing to CRAN.

**Comment by SouzaBB** [comment]
Hi @vplagnol, thanks for replying.
Unfortunatelly, still not working! Got the same error.

My command:
`data(exons.hg19)`
`my.counts <- getBamCounts(bed.frame = exons.hg19, bam.files = "/path/to/my_bam_list", include.chr = F, referenceFasta = "/path/to/hg19.fa"`

**Comment by vplagnol** [comment]
Yes so ExomeDepth has not been updated. You should see:
```
> packageVersion("ExomeDepth")
[1] ‘1.1.13’
```

Are you sure 
` devtools::install_github("vplagnol/ExomeDepth")`
completed without errors?

**Comment by SouzaBB** [comment]
Did everything again, ExomeDepth has updated.

`other attached packages:
[1] ExomeDepth_1.1.13`

```
Still having the same error
Erro: RangedData objects are deprecated and the rownames setter for
  RangedData objects is now defunct. Please migrate your code to use
  GRanges or GRangesList objects instead. See IMPORTANT NOTE in
  ?RangedData

Além disso: Warning messages:

1:   RangedData objects are deprecated. Please migrate your code to use
  GRanges or GRangesList objects instead. See IMPORTANT NOTE in
  ?RangedData 
```

**Comment by vplagnol** [comment]
It's strange... I removed any occurrence of RangedData... Nothing is left in the code.
I don't understand where that may be coming from.

**Comment by SouzaBB** [comment]
Is it working ok for you? Maybe the error comes from my input data!?

**Comment by vplagnol** [comment]
It works for me but with R 3.5. It is R 3.6 that makes the RangedData deprecated. So if you still see some RangedData somewhere, I must be doing something wrong... I just can't figure out where!

**Comment by vplagnol** [comment]
OK I installed R 3.6 and it works fine with version 1.13 of ExomeDepth.
I suspect something is not right about your setup. My test is very basic:
```
library(ExomeDepth)
myres <- getBamCounts(bed.file = 'data/bedFiles/exons_hg19_small.bed', bam.files = c('data/small_exome.bam', 'data/small_exome.bam'),
                         min.mapq = 20, read.width = 300, include.chr = FALSE, referenceFasta = 'data/hg19_nochr.fa')
```
but it works fine.

**Comment by SouzaBB** [comment]
Hi @vplagnol,
Worked... I've found a problem with my syntax, now everything is fine! Thank you very much for your patience in solving the issue!

**Comment by vplagnol** [comment]
Ah OK. I wanted to submit version 1.13 to CRAN but unfortunately:
```
The submission server team is on vacation from Dec 20, 2019 to Jan 6, 2020
During this time the submission of packages is not possible.
```
It will have to wait until next year. Meanwhile, use the version on github...

**Comment by SouzaBB** [comment]
Ok, that's the version I'm using!

Thanks.

**Comment by vplagnol** [comment]
Last ranged objects gone in 1.1.15 (on its way to CRAN), so closing that issue.
